### ISSUE TITLE
Accent color for Menu item?

### ISSUE THREAD

**Issue by trietbui85** [negusoft/holoaccent#23]
As I see in Android ActionBar Style Generator (http://jgilfelt.github.io/android-actionbarstylegenerator), we can customize menu item background (is "Popup color" section in above link).

But in HoloAccent, although I choose a custom color but background of Menu item still is holo color (`#33b5e5`).

I don't know if it's possible to do this with HoloAccent?

**Comment by blurkidi** [comment]
The background color is holo blue? (#33b5e5) Could you provide a sample code to show it? Some screenshot? ...

The expected behavior it that it is either light grey or black, depending on the theme you have selected. Meaning that is not customized, it should be the original system background for the parent theme.

**Comment by trietbui85** [comment]
OK I see. If expected behavior is the background color only depends on Dark or Light theme, not depend on selected accent color, then it's fine.
