### ISSUE TITLE
Assets not generated on L-Preview

### ISSUE THREAD

**Issue by dadino** [negusoft/holoaccent#30]
I don't think it is an high priority issue, but running an application on a Nexus 5 with Android L-Preview doesn't generate button assets and ActionBar background colors.
Buttons appear like white boxes, ActionBar is black.

**Comment by blurkidi** [comment]
Thanks for the report. Seen the new Material theme in the L release, it seems like HoloAccent will be useless in the future, which is great news! I guess that the library will have to be adapted so that it is only effective for SDK versions lower than 20.
I don't have the chance to play with a Andrlid L build yet so I can't tell how much it will take to adapt it.

**Comment by dadino** [comment]
On the contrary, I think it will be essential. You have the base to rebuilt what L does with colors. Right now I'm using Theme.Material in value-v21, while using HoloAccent in other versions and it works great.
An idea could be to replicate the color scheme used in L, with ColorPrimary, ColorPrimaryDark, ColorAccent, ecc and provide assets following the same principles. This could be a great tool to mantain mental sanity while targeting multiple versions.

**Comment by gonemad** [comment]
I agree that getting this to run on L is important.  I'd also still like to use colored holo themes in android L if its what my users want.  Amazingly enough there are plenty of users who do not like Material and still prefer holo.  I think as long as holo is a valid theme in android.. this library should stay supported

**Comment by blurkidi** [comment]
The fixes for Android Lollipop are available in the dev branch. I would wait to test it in an actual device before creating a release.
