### ISSUE TITLE
Add support for android:ListSeparatorTextView

### ISSUE THREAD

**Issue by Wolftein** [negusoft/holoaccent#35]
"android:ListSeparatorTextView" is being used by PreferenceFragment for each PreferenceCategory.

**Comment by blurkidi** [comment]
For what I see "listSeparatorTextViewStyle" attribute is not colored, so it doesn't need any support. I guess the question is whether it is worth it to include a colored version of that style in HoloAccent.

I could create a style like "HoloAccent.TextView.ListSeparator" so that it is easy to customize it. You would have to add the following attribute to your theme:

<item name="android:listSeparatorTextViewStyle">@style/HoloAccent.TextView.ListSeparator</item>

**Comment by blurkidi** [comment]
Ok, I implemented "HoloAccent.TextView.ListSeparator" and "HoloAccent.TextView.ListSeparator.Dark". It is available in the "dev" branch. You can assing any of them to listSeparatorTextViewStyle in your theme:

<style name="MyTheme" parent="Theme.HoloAccent.Light.ColoredActionBar.Inverse">
        <item name="android:listSeparatorTextViewStyle">@style/HoloAccent.TextView.ListSeparator.Dark</item
</style>

**Comment by Wolftein** [comment]
Awesome, now i'm able to fully customize my preference screen :) Thank you.

**Comment by Wolftein** [comment]
Is the "Dev" branch available for Maven and Gradle?

**Comment by blurkidi** [comment]
No, but I will soon create a new release that will include this issue and upload it to maven central.

**Comment by blurkidi** [comment]
I guess you already realised but v1.0.1 is released and it includes the new styles.
