### ISSUE TITLE
Custom attr clash with another library

### ISSUE THREAD

**Issue by intrications** [negusoft/holoaccent#5]
I'm trying to use this library along with https://github.com/johnkil/Android-RobotoTextView

However, I'm getting this error:

```
Attribute "typeface" has already been defined
```

I can fix this by prefixing typeface in one of the libraries (e.g. ha__typeface) but wondered if you knew of any better solution.

**Comment by intrications** [comment]
Matching issue on other library: https://github.com/johnkil/Android-RobotoTextView/issues/19

**Comment by blurkidi** [comment]
Ok, I thought that since the 'typeface attribute' (like some others) is inside a 'declare-styleable', it wouldn't conflict with other attributes. But it is a common issue in library projects:

https://groups.google.com/forum/#!msg/adt-dev/HeM0aptfddY/R8a18AwE7MQJ

The common solution is, as you mention, to prefix the attributes and I recommend that you do that for the time being.

In this concrete case, all the attributes within the AccentSwitch and  TextAppearanceAccentSwitch 'declare-styleable' blocks are just copies of native android attributes. Therefore, the solution will be to reuse them by adding the "android:" namespace prefix.

The fix will soon be available in the dev branch and incuded in the next release. Thanks for reporting!

**Comment by intrications** [comment]
Thanks. I was hoping I wouldn't have to keep my own fork with the fix because you are still making lots of updates to the library (which is great).

It is an amazing library, by the way. Makes it easy to test out different styles.

**Comment by blurkidi** [comment]
Ok, the fix is in the 'dev' branch now. It is the only change from v0.8 so it should be as stable. You can check out the commit if you want:

commit: 686d767a719d6492a896c3874f8603419673a12a

**Comment by intrications** [comment]
@blurkidi 

Thanks. Haven't fully tested but works perfectly so far.
